version: '3.8'
services:
  db:
    image: postgres:16.8
    container_name: postgres_db
    environment:
      POSTGRES_DB: template_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: springboot_api
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/template_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data: