{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  labels:
    {{- include "spring-boot-template.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.data }}
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }} 