name: 'CI/CD (Pull Request)'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  revision:
    name: Revision
    runs-on: [ ubuntu-latest ]
    outputs:
      revision: ${{ steps.revision.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0

      - name: Get revision
        id: revision
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "revision=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            REVISION=$(git describe --tags --always)
            echo "revision=$REVISION" >> $GITHUB_OUTPUT
          fi

  format:
    name: Format Check
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven & Java
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-setup@main

      - name: Run Spotless Check
        run: mvn -B -ntp spotless:check

  test:
    name: Tests
    runs-on: [ ubuntu-latest ]
    needs: [ revision, format ]
    outputs:
      revision: ${{ needs.revision.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven & Java
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-setup@main

      - name: Run Unit Tests
        run: mvn -B -ntp clean test -Drevision=${{ needs.revision.outputs.revision }}

      - name: Upload target directory
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: target

      - name: Run Integration Tests
        run: mvn -B -ntp failsafe:integration-test failsafe:verify -Drevision=${{ needs.revision.outputs.revision }}

      - name: Publish reports
        if: always() && github.event_name == 'pull_request'
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-failsafe-surefire-report@main

  sonar:
    name: SonarQube Analysis
    runs-on: [ ubuntu-latest ]
    needs: [ test ]
    outputs:
      revision: ${{ needs.test.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download target directory
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: target

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  helm:
    name: Helm Validation
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm