name: "CI/CD (Pull Request)"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci-cd:
    name: CI/CD
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/ci-cd-pr.yml@main
    secrets: inherit
