name: 'CI/CD (Non-Release)'

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  revision:
    name: Revision
    runs-on: [ ubuntu-latest ]
    outputs:
      revision: ${{ steps.revision.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0

      - name: Get revision
        id: revision
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "revision=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            REVISION=$(git describe --tags --always)
            echo "revision=$REVISION" >> $GITHUB_OUTPUT
          fi

  format:
    name: Format Check
    runs-on: [ ubuntu-latest ]
    needs: [ revision ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven & Java
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-setup@main

      - name: Run Spotless Check
        run: mvn -B -ntp spotless:check

  test:
    name: Tests
    runs-on: [ ubuntu-latest ]
    needs: [ revision, format ]
    outputs:
      revision: ${{ needs.revision.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven & Java
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-setup@main

      - name: Run Unit Tests
        run: mvn -B -ntp clean test -Drevision=${{ needs.revision.outputs.revision }}

      - name: Upload target directory
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: target

      - name: Publish reports
        if: always() && github.event_name == 'pull_request'
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-failsafe-surefire-report@main

  sonar:
    name: SonarQube Analysis
    runs-on: [ ubuntu-latest ]
    needs: [ test ]
    outputs:
      revision: ${{ needs.test.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download target directory
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: target

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [ sonar ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven & Java
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-setup@main

      - name: Package
        run: mvn -B -ntp clean package -Drevision=${{ needs.sonar.outputs.revision }} -DskipTests=true

      - name: Docker build & push
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/docker-build-push@main
        with:
          image-repo-name: spring-boot-template
          image-tag: ${{ needs.sonar.outputs.revision }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}

  helm:
    name: Helm Package & Push
    runs-on: ubuntu-latest
    needs: [ sonar ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Helm package & push
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/helm-package-push@main
        with:
          chart-version: ${{ needs.sonar.outputs.revision }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}