name: "Docker ACR Push"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  revision:
    name: Revision
    runs-on: [ubuntu-latest]
    outputs:
      revision: ${{ steps.revision.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: "true"
          fetch-depth: 0

      - name: Get revision
        id: revision
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "revision=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            REVISION=$(git describe --tags --always)
            echo "revision=$REVISION" >> $GITHUB_OUTPUT
          fi

  docker-acr-push:
    name: Docker ACR Push
    needs: revision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Maven & Java
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/mvn-setup@main
        with:
          java-version: 24
          maven-version: 3.9.6

      - name: Package
        run: mvn -B -ntp clean package -Drevision=${{ needs.revision.outputs.revision }} -DskipTests=true

      - name: Build and push Docker image
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/docker-build-push@main
        with:
          cloud-provider: azure
          image-repo-name: spring-boot-template
          image-tag: ${{ needs.revision.outputs.revision }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
