name: PR checks

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pr-checks:
    name: PR format
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/pr-checks.yml@main
    secrets: inherit
