name: 'Version Updater'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  version-updater:
    name: Update Version
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Get Token From GitHub APP
        uses: unir-tfm-devops/reusable-github-actions/.github/actions/version-updater@main
        with:
            version: 1.0.0
            app-id: ${{ vars.UNIR_TFM_APP_ID }}
            private-key: ${{ secrets.UNIR_TFM_APP_PRIVATE_KEY }}